"use client"
import { Providers } from '@/store/provider'
import './globals.css'
import "react-lazy-load-image-component/src/effects/blur.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Footer from '@/Static/Fotter/Fotter';
import { getHomeHeaders, getMainCat, getMostViewed } from '@/store/CategoriesSlice';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
 
  return (
    <>
    <html lang="ar" dir="rtl">
    <head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
    </head>
    <body>
      
    <Providers>
      {children}
    </Providers>
    <Footer />  
    {/* <style jsx global >
        {
          `
          .p-slider:not(.p-disabled) .p-slider-handle:hover {
            color: black;
            background-color: black;
            border-color: black;
          }
          .p-slider .p-slider-handle:focus {
            box-shadow: 0 0 0 0.2rem #d2d4da;
          }
         AccordionDemo.css 
          .accordion-demo .accordion-custom i, .accordion-demo .accordion-custom span {
            vertical-align: middle;
          }
          
          .accordion-demo .accordion-custom span {
            margin: 0 .5rem;
          }
          .accordion-demo .p-accordion p {
            line-height: 1.5;
            margin: 0;
          }
          .p-accordion-tab  {
            margin: 15px 0 !important;
          }
          .p-accordion-content .accContainer {
            padding: 10px;
          }
          
          .p-accordion-header-link {
            flex-direction: row-reverse;
            justify-content: space-between;
          }
          
          .p-accordion .p-accordion-header .p-accordion-header-link .pi-chevron-down {
            transform: rotate(180deg);
            -webkit-transform: rotate(180deg);
            -moz-transform: rotate(180deg);
            -ms-transform: rotate(180deg);
            -o-transform: rotate(180deg);
          }  
          
          .p-accordion .p-accordion-header .p-accordion-header-link .pi-chevron-right {
            transform: rotate(90deg);
            -webkit-transform: rotate(90deg);
            -moz-transform: rotate(90deg);
            -ms-transform: rotate(90deg);
            -o-transform: rotate(90deg);
          }
          .p-accordion-tab-active .p-accordion-header a {
            color: var(--main-color) !important;
          }
          .p-accordion .p-highlight .p-accordion-header-link {
            background-color: white !important;
            border-bottom-color: transparent !important;
          }
          
          .p-accordion .p-accordion-header:not(.p-disabled) .p-accordion-header-link:focus {
            box-shadow: none !important;
          }
          .p-accordion .p-accordion-content {
            padding: 10px 1rem 1.25rem;
          }
          
          .p-rating.p-readonly .p-rating-icon {
            font-size: 10px;
            color: var(--bs-yellow);
            margin: 0 2px ;
          }
          NavBarComp .Souq  .lazy-load-image-background.blur.lazy-load-image-loaded  {
            height: 50px !important;
            width: 120px !important;
          }
       
          .p-slider .p-slider-handle {
            border-color: black;
          }
          .ProductCard .Card_img .lazy-load-image-background.blur.lazy-load-image-loaded {
            min-width: 100px !important;
            min-height: 100px !important;
            max-width: 135px !important;
            max-height: 135px !important;
          }
        
          .Last_div .Card_img .lazy-load-image-background.blur.lazy-load-image-loaded {
            width: 70px !important;
            height: 70px !important;
        }
          .offcanvas-body {
            direction: rtl ;
          }
          .Last_div .Card_img .lazy-load-image-background.blur.lazy-load-image-loaded {
            width: 100px !important;
            height: 100px !important;
        }
        @media (min-width: 10px) and (max-width: 765.98px) { 

          .ProductCard .Card_img .lazy-load-image-background.blur.lazy-load-image-loaded {
            min-width: 100px !important;
            min-height: 100px !important;
            max-width: 135px !important;
            max-height: 135px !important;
          }
        
          .Last_div .Card_img .lazy-load-image-background.blur.lazy-load-image-loaded {
            width: 70px !important;
            height: 70px !important;
        }
        }

        .p-rating.p-readonly .p-rating-icon {
          font-size: 12px;
          color: var(--bs-yellow);
          margin: 2px;
        }
        .p-rating .p-rating-icon.pi-star-fill {
          color: var(--bs-yellow) !important;
        }
        .offcanvas-body {
          padding: 20px 0;
        
        }
        
        .Links-nav-container {
          display: flex;
          flex-direction: column;
          justify-content: space-around;
          align-items: center;
          width: 100%;
        
        }
        .Links-nav-container a {
          padding: 13px !important;
          border-bottom: 1px solid rgb(1 1 1 / 23%);
          width: 100%;
          display: flex;
          justify-content: flex-start;
          align-items: center;
        }
        .Links-nav-container a svg {
          margin-left: 30px;
        }
        .offcanvas-header {
          border-bottom: 1px solid rgb(1 1 1 / 23%);
          padding: 22px 15px;
          justify-content: flex-end;
        }
        .offcanvas-title {
          flex-basis: 61%;
          text-align: left;
        }
        @media (min-width: 10px) and (max-width: 765.98px) { 
          .NavBar {
            position: sticky;
            top: 0;
            z-index: 999;
          }
         
        .NavBarComp .Souq  .lazy-load-image-background.blur.lazy-load-image-loaded  {
          height: 50px !important;
          width: 120px !important;
        }
      }
    
     
      .slider-header-container {
        display: flex;
        justify-content: space-between;
  
        margin-bottom: 10px !important;
      }
      .p-slider .p-slider-handle:focus {
        box-shadow: 0 0 0 0.2rem #d2d4da;
      }
      .slider-header-container span {
        background-color: #F4F4F4;
        padding: 5px 10px;
      }
      .p-slider:not(.p-disabled) .p-slider-handle:hover {
        color: black;
        background-color: black;
        border-color: black;
      }
      .p-slider .p-slider-handle:focus {
        box-shadow: 0 0 0 0.2rem #d2d4da;
      }
      .accordion-demo .accordion-custom i, .accordion-demo .accordion-custom span {
        vertical-align: middle;
      }
      
      .accordion-demo .accordion-custom span {
        margin: 0 .5rem;
      }
      
      .accordion-demo .p-accordion p {
        line-height: 1.5 !important;
        margin: 0;
      }
      .p-accordion-tab  {
        margin: 15px 0;
      }
      .p-accordion-content .accContainer {
        padding: 10px  !important;
      }
      
      .p-accordion-header-link {
        flex-direction: row-reverse  !important;
        justify-content: space-between  !important;
      }
      
      .p-accordion .p-accordion-header .p-accordion-header-link .pi-chevron-down {
        transform: rotate(180deg);
        -webkit-transform: rotate(180deg);
        -moz-transform: rotate(180deg);
        -ms-transform: rotate(180deg);
        -o-transform: rotate(180deg);
      }  
      
      .p-accordion .p-accordion-header .p-accordion-header-link .pi-chevron-right {
        transform: rotate(90deg);
        -webkit-transform: rotate(90deg);
        -moz-transform: rotate(90deg);
        -ms-transform: rotate(90deg);
        -o-transform: rotate(90deg);
      }
      .p-accordion-tab-active .p-accordion-header a {
        color: var(--main-color) !important;
      }
      .p-accordion .p-highlight .p-accordion-header-link {
        background-color: white !important;
        border-bottom-color: transparent !important;
      }
      
      .p-accordion .p-accordion-header:not(.p-disabled) .p-accordion-header-link:focus {
        box-shadow: none !important;
      }
      .p-accordion .p-accordion-content {
        padding: 10px 1rem 1.25rem;
      }
      .p-accordion-tab {
        margin: 0;
      }
      .main-heading {
        color: var(--main-color);
        font-size: 30px;
        margin: 50px auto;
      }
      .modal-backdrop.show {
        z-index: 9;
      }
      .disFlex {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 0;
  }
  .Navitem {
    font-size: 20px;
    font-weight: bold;
    padding: 5px 15px !important;
  }
  .NavBar .nav-link:hover , .NavBarComp .nav-link:hover{ 
    color: var(--main-color) !important;
  }  
      .p-rating.p-readonly .p-rating-icon {
        font-size: 10px;
        color: var(--bs-yellow);
        margin: 0 2px ;
      }
      .infinite-scroll-component {
        overflow-x:hidden !important ;
      }
      .drop-section-menu ul li a {
        justify-content: flex-end;
      }
          `
        }
      </style>
     */}
    </body>
  </html>

  </>
  )
}
